### PR TITLE
Add home page html

### PR DESCRIPTION
**Pull request by james-woo**

### CODE REVIEW

**Comment by cpjk** [comment]
I just tested this and it looks like the dropdown on the right side of the navbar doesn't work when a user is logged in. 

Normally, when a user is logged in, there is a dropdown on the right side of the navbar that has the user's profile page and a logout link.

It would be awesome if you could add another commit that fixes this.

This is probably a bootstrap problem.

**Comment by james-woo** [comment]
I tested the dropdown menu when logged in, and it seems to work. Could you provide more information?

Also, I have removed the items as requested, I will push these changes.

**Comment by cpjk** [comment]
Umm, I'm not sure what you did, but the second commit did not delete the files.
You just need to rm the files in question, git add them, then git commit and push.

I think the second commit added a second ds_store file as well :(

**Comment by cpjk** [comment]
There are actually several ds_store files it looks like. This is probably happening because you did

```
git add .
```

 but you have not told git to ignore .ds_store files, so it thinks you want to track them

It's probably a good idea to add that filename to your global .gitignore file.

**Pull request closed without merging**
